# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75539bb560b53e8f831d4a354a7f6c36f902bca96cfd6c5b0c254aa5e4d65af37eca99fa70f05e914a87772814894daa6a9165a9b665525801d78175266f7c88

test:
  secret_key_base: 634403da43c1722c432994e8d76603800c0fe7983de654d38d1077559d7284854acc9ac82a3103c5969faa7ba598aea97a0bc78d9d394e38a8d951063863bd53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
